/**
* Footer include
* ------------------
*/
(function(){


var str='';
str+='<div class="custom_footer"><!-- custom_footer -->';
str+='  <!-- footer -->';
str+='  <div id="com_footer" class="renewal"><!-- #com_footer -->';
str+='      <!-- 마케팅 팝업 : 메인에만 노출 -->';
str+='		<div class="marketing_popup_box">';
str+='			<div aria-hidden="false" class="marketing_popup_inner" id="slide_popup_02">';
str+='				<div class="popup_content">';
str+='					<!-- case 1 : popup 다건 -->';
str+='					<div id="slider_01" class="slider_wrap">';
str+='						<div class="tab_cont">';
str+='							<div role="tabpanel" class="cmm-tab-panel">';
                                    // 2022-10-20 : 웹접근성 관련 role="button" 삽입
str+='								<a href="javascript:void(0):;" role="button">';
str+='									<div class="slide slide01">	';
str+='									    <img src="../../../../src/assets/images/newmain/img/img_slide_img01.png" alt="" />';
str+='										<p>신차 견적내고 대출까지 바로! 신차</p>';
str+='									</div>';
str+='								</a>';
str+='							</div>';
str+='							<div role="tabpanel" class="cmm-tab-panel">';
                                    // 2022-10-20 : 웹접근성 관련 role="button" 삽입
str+='								<a href="javascript:void(0):;" role="button">';
str+='									<div class="slide slide02">';	
str+='									    <img src="../../../../src/assets/images/newmain/img/img_slide_img02.png" alt="" />';
str+='										<p>글자 2 글자 2 글자</p>';
str+='									</div>';
str+='								</a>';
str+='							</div>';
str+='						</div>';
str+='					</div>';
str+='					<!-- case 2 : popup 다건 -->';
str+='					<!--<div id="slider_01" class="slider_wrap slider_solo">';
str+='						<div class="tab_cont">';
str+='							<div role="tabpanel" class="cmm-tab-panel">';
                                    // 2022-10-20 : 웹접근성 관련 role="button" 삽입
str+='								<a href="javascript:void(0):;" role="button">';
str+='									<div class="slide slide01">	';
str+='									    <img src="../../../../src/assets/images/newmain/img/img_slide_img01.png" alt="" />';
str+='										<p>신차 견적내고 대출까지 바로!</p>';
str+='										<button type="button">바로가기</button>';
str+='									</div>';
str+='								</a>';
str+='							</div>';
str+='						</div>';
str+='					</div>-->';
str+='				</div>';
str+='				<a href="javascript:void(0);" class="btn_close"><span class="blind">닫기</span></a>';
str+='			</div>';
str+='		</div>';
str+='      <!--// 마케팅 팝업 : 메인에만 노출 -->';
str+='      <div class="footer-depth1"><!-- 1depth -->';
str+='          <ul>';
str+='              <li class="item1"><a href="javascript:void(0);" title="선택됨" role="button">자산</a></li><!-- [개발자 전달] 기본값 active -->';
str+='              <li class="item2"><a href="javascript:void(0);" role="button">지출</a></li>';
str+='              <li class="item3"><a href="javascript:void(0);" role="button">금융생활</a></li>';
str+='              <li class="item4"><a href="javascript:void(0);" role="button">제휴서비스</a></li>';
str+='              <li class="item5 allmenu"><a href="javascript:void(0);" role="button">더보기</a></li>';
str+='          </ul>';
str+='      </div><!-- //1depth -->';
str+='  </div><!-- // #com_footer -->';
str+='  <!-- //footer -->';
str+='  <div class="allmenu-wrapper"><!-- 전체메뉴 영역 -->';
str+='      <div class="ios"><!-- [개발자 전달] 스크롤 버그 수정용 -->';
str+='          <div class="custom_fiexd_wrap"><!-- custom_fiexd_wrap -->';
str+='              <div class="custom_fiexd"><!-- custom_fiexd -->';
str+='                  <div class="allmenu-top"><!-- allmenu-top -->';
str+='                      <div class="menu_area">';
str+='                          <div class="user_info">    ';
str+='                              <p class="user_box_top"><strong class="user_nm">김농협님 반갑습니다.</strong></p>';
str+='                              <p class="user_nb">고객번호 1001154124</p>';
str+='                          </div>';
str+='                          <ul class="top_menu">';
str+='                              <li class="alram">';
str+='                                  <a href="javascript:void(0);" class="active" title="새알림" role="button">';
str+='                                      <span class="text_over">알림</span>';
str+='                                  </a>';
str+='                              </li>';
str+='                          </ul>';
str+='                      </div>';
str+='                      <div class="section_list_wrap">';
str+='                          <div>';
str+='                              <ul class="section_list">';
str+='                                  <li>';
str+='                                      <a href="javascript:void(0);" role="button">';
str+='                                          <span class="list_box all profile">';
str+='                                              <strong><span></span></strong>';
str+='                                              <span class="list_tit">MY프로필</span>';
str+='                                          </span>';
str+='                                      </a>';
str+='                                  </li>';
str+='                                  <li>';
str+='                                      <a href="javascript:void(0);" role="button">';
str+='                                          <span class="list_box all money">';
str+='                                              <strong><span></span></strong>';
str+='                                              <span class="list_tit">연결기관관리</span>';
str+='                                          </span>';
str+='                                      </a>';
str+='                                  </li>';           
str+='                                  <li>';
str+='                                      <a href="javascript:void(0);" role="button">';
str+='                                          <span class="list_box all credit">';
str+='                                              <strong><span class="num">940</span><span class="unit">점</span></strong>';
str+='                                              <span class="list_tit">신용점수</span>';
str+='                                          </span>';
str+='                                      </a>';
str+='                                  </li>';
str+='                              </ul>';
str+='                          </div>';
str+='                      </div>';
str+='                  </div><!--// allmenu-top -->';
str+='                  <div class="com_inner credit_list_box all_Menu"><!-- com_inner credit_list_box all_Menu -->';
str+='                      <div class="com_box_nobox all_Menu_inner01">';
str+='                          <div class="list_type_box">';
str+='                              <div class="new_tit_area"><div class="tit"><span>자산</span></div></div>';
str+='                                  <ul class="list_type_02">';
str+='                                      <li class="all_menu_list01"><a href="javascript:void(0);">전체자산</a></li>';
str+='                                      <li class="all_menu_list02"><a href="javascript:void(0);">자산현황</a></li>';
str+='                                      <li class="all_menu_list03"><a href="javascript:void(0);">부채현황</a></li>';
str+='                                      <li class="all_menu_list04"><a href="javascript:void(0);">자산진단</a></li>';
str+='                                  </ul>';
str+='                              </div>';
str+='                          </div>';
str+='                          <div class="com_box_nobox all_Menu_inner02">';
str+='                              <div class="list_type_box">';
str+='                                  <div class="new_tit_area">';
str+='                                      <div class="tit"><span>지출</span></div>';
str+='                                  </div>';
str+='                                  <ul class="list_type_02">';
str+='                                      <li class="all_menu_list01"><a href="javascript:void(0);">금융달력</a></li>';
str+='                                      <li class="all_menu_list02"><a href="javascript:void(0);">지출내역</a></li>';
str+='                                      <li class="all_menu_list03"><a href="javascript:void(0);">지출분석</a></li>';
str+='                                      <li class="all_menu_list04"><a href="javascript:void(0);">숨김보관함</a></li>';
str+='                                  </ul>';
str+='                              </div>';
str+='                          </div>';
str+='                          <div class="com_box_nobox all_Menu_inner03">';
str+='                              <div class="list_type_box">';
str+='                                  <div class="new_tit_area">';
str+='                                      <div class="tit"><span>금융생활</span></div>';
str+='                                  </div>';
str+='                                  <ul class="list_type_02">';
str+='                                      <li class="all_menu_list01"><a href="javascript:void(0);">나의목표</a></li>';
str+='                                      <li class="all_menu_list02"><a href="javascript:void(0);">상품추천</a></li>';
str+='                                      <li class="all_menu_list03"><a href="javascript:void(0);">금융통통</a></li>';
str+='                                      <li class="all_menu_list04"><a href="javascript:void(0);">금융브리핑</a></li>';
str+='                                  </ul>';
str+='                              </div>';
str+='                          </div>';
str+='                          <div class="com_box_nobox all_Menu_inner04">';
str+='                              <div class="list_type_box">';
str+='                                  <div class="new_tit_area">';
str+='                                      <div class="tit"><span>제휴서비스</span></div>';
str+='                                  </div>';
str+='                                  <ul class="list_type_02">';
str+='                                      <li class="all_menu_list01"><a href="javascript:void(0);">NH콕마이카</a></li>';
str+='                                      <li class="all_menu_list02"><a href="javascript:void(0);">NH콕부동산</a></li>';
str+='                                      <li class="all_menu_list03"><a href="javascript:void(0);">귀농귀촌</a></li>';
str+='                                      <li class="all_menu_list04"><a href="javascript:void(0);">마이농가</a></li>';
str+='                                  </ul>';
str+='                              </div>';
str+='                          </div>';
str+='                          <div class="com_box_nobox all_Menu_inner05">';
str+='                              <div class="list_type_box">';
str+='                                  <div class="new_tit_area">';
str+='                                      <div class="tit"><span>고객센터</span></div>';
str+='                                  </div>';
str+='                                  <ul class="list_type_02">';
str+='                                      <li class="all_menu_list01"><a href="javascript:void(0);">새소식</a></li>';
str+='                                      <li class="all_menu_list02"><a href="javascript:void(0);">자주하는 질문</a></li>';
str+='                                  </ul>';
str+='                          </div>';
str+='                      </div>';
str+='                      <div class="com_box_nobox all_Menu_inner06">';
str+='                          <div class="list_type_box">';
str+='                              <div class="new_tit_area">';
str+='                                  <div class="tit"><span>약관 및 동의서</span></div>';
str+='                              </div>';
str+='                              <ul class="list_type_02">';
str+='                                  <li class="all_menu_list01"><a href="javascript:void(0);">약관 및 동의서</a></li>';
str+='                                  <li class="all_menu_list02"><a href="javascript:void(0);">제3자정보제공동의</a></li>';
str+='                              </ul>';
str+='                          </div>';
str+='                      </div>';
str+='                  </div><!--// com_inner credit_list_box all_Menu -->';
str+='                  <div class="com_inner credit_list_box all_Menu com_bg_type02">';
str+='                      <div class="com_btn_area">';
str+='                          <a href="javascript:void(0);" class="com_btn_round"><span class="ico type05">마이데이터 서비스 이용안내</span></a>';
str+='                      </div>';
str+='                  </div>';
str+='                  <div class="closed-wrap all_Menu">';
str+='                      <ul>';
str+='                          <li><a href="javascript:void(0);">서비스해지</a></li>';
str+='                      </ul>';
str+='                  </div>';
str+='                  <div class="com_btn_area all_Menu">';
str+='                      <a href="javascript:void(0);" class="all_close"><span class="blind">전체메뉴닫기</span></a>';
str+='                  </div><!--// 닫기 E -->';
str+='              </div><!--// custom_fiexd -->';
str+='          </div><!--// custom_fiexd_wrap -->';
str+='      </div><!--// [개발자 전달] 스크롤 버그 수정용 -->';
str+='  </div><!-- //전체메뉴 영역 -->';
str+='</div><!-- custom_footer -->';
document.write(str);
})();