/**
* Footer include
* ------------------
*/
(function(){


var str='';
str+='		<!-- footer -->';
str+='      <div class="footer-wrap">';
str+='          <div class="menu_area allmenu">';
str+='              <ul class="top_menu">';
str+='                  <li class="alram">';
str+='                      <a href="javascript:void(0);" class="active" title="새알림" role="button"><span class="text_over">알림</span></a><!-- [개발자 전달] 알림 있으면 class active 추가하세요 -->';
str+='                  </li>';
str+='                  <li class="menu">';
str+='                      <a href="javascript:void(0);" role="button"><span class="text_over">전체메뉴</span></a>';
str+='                  </li>';
str+='              </ul>';
str+='          </div><!-- //footer GNB -->';
str+='          <div class="footer-contents">';
str+='              <p class="item1 active"><!-- [개발자 전달] 기본값 active -->';
str+='                  <strong>흩어져 있는 나의 자산<br>농협 마이데이터로 모아보세요!</strong>';
str+='              </p>';
str+='              <p class="item2">';
str+='                  <strong>손쉬운 가계부<br>달력으로 관리하세요!</strong>';
str+='              </p>'; 
str+='              <p class="item3">';
str+='                  <strong>금융목표를 세우고 달성하는<br>즐거움! 나의목표 세우기!</strong>';
str+='              </p>';
str+='              <p class="item4">';
str+='                  <strong>데이터로 키우는 마이농가<br>영농일지로 시작하세요!</strong>';
str+='              </p>';
str+='          </div><!-- //footer contents -->';      
str+='          <div class="footer-depth2">';
str+='              <ul class="cnt4 active"><!-- [개발자 전달] 메뉴4개일때 cnt4 --><!-- [개발자 전달] 기본값 active -->';
str+='                  <li class="item1"><a href="javascript:void(0);" role="button">전체</a></li>';
str+='                  <li class="item2"><a href="javascript:void(0);" role="button">자산</a></li>';
str+='                  <li class="item3"><a href="javascript:void(0);" role="button">부채</a></li>';
str+='                  <li class="item4"><a href="javascript:void(0);" role="button">진단</a></li>';
str+='              </ul>';            
str+='              <ul class="cnt3 cate2"><!-- [개발자 전달] 메뉴3개일때 cnt3 -->';
str+='                  <li class="item1"><a href="javascript:void(0);" role="button">달력</a></li>';
str+='                  <li class="item2"><a href="javascript:void(0);" role="button">지출</a></li>';
str+='                  <li class="item3"><a href="javascript:void(0);" role="button">분석</a></li>';
str+='              </ul>';            
str+='              <ul class="cnt4-2 cate3"><!-- [개발자 전달] 메뉴3개일때 cnt3 -->';
str+='                  <li class="item1"><a href="javascript:void(0);" role="button">나의목표</a></li>';
str+='                  <li class="item2"><a href="javascript:void(0);" role="button">상품추천</a></li>';
str+='                  <li class="item3"><a href="javascript:void(0);" role="button">금융통통</a></li>';
str+='                  <li class="item4"><a href="javascript:void(0);" role="button">자동차관리</a></li>';
str+='              </ul>';
str+='              <!-- [개발자 전달] 조합원 있을 때 S -->';            
str+='              <!-- [개발자 전달] 메뉴5개일때 cnt5 -->';
str+='              <ul class="cnt5">';
str+='                  <li class="item2"><a href="javascript:void(0);" role="button">영농달력</a></li>';
str+='                  <li class="item3"><a href="javascript:void(0);" role="button">영농일지</a></li>';
str+='                  <li class="item4"><a href="javascript:void(0);" role="button">손익분석</a></li>';           
str+='                  <li class="item5"><a href="javascript:void(0);" role="button">농기계임대</a></li>';
str+='                  <li class="item6"><a href="javascript:void(0);" role="button">정책자금</a></li>';
str+='              </ul>';
str+='              <!-- [개발자 전달] 조합원 없을 때 S -->';             
str+='              <ul class="cnt4"> <!-- [개발자 전달] 메뉴4개일때 cnt4 -->';
str+='                  <li class="item1"><a href="javascript:void(0);" role="button">영농달력</a></li>';
str+='                  <li class="item2"><a href="javascript:void(0);" role="button">영농일지</a></li>';
str+='                  <li class="item3"><a href="javascript:void(0);" role="button">농기계임대</a></li>';
str+='                  <li class="item4"><a href="javascript:void(0);" role="button">정책자금</a></li>';
str+='              </ul>';
str+='              // [개발자 전달] 조합원 없을 때 E -->';
str+='          </div><!-- //2depth -->';
str+='      </div><!-- // .footer-wrap E -->';
str+='      <div id="com_footer"><!-- // 하단 고정 -->';
str+='          <div class="footer-cancle">';
str+='              <button class="cancle"><span class="blind">푸터메뉴닫기</span></button>';
str+='          </div>';
str+='          <div class="footer-depth1">';
str+='              <ul>';
str+='                  <li class="item1"><a href="javascript:void(0);" title="선택됨" role="button">나의자산</a></li><!-- [개발자 전달] 기본값 active -->';
str+='                  <li class="item2"><a href="javascript:void(0);" role="button">가계부</a></li>';
str+='                  <li class="item3"><a href="javascript:void(0);" role="button">금융생활</a></li>';
str+='                  <li class="item4"><a href="javascript:void(0);" role="button">마이농가</a></li>';
str+='                  <li class="item5 allmenu"><a href="javascript:void(0);" role="button"></a></li>';
str+='              </ul>';
str+='          </div><!-- //1depth -->';
str+='      </div><!-- // #com_footer E -->';            
str+='		<!-- //footer -->';
str+='      <!-- 전체메뉴 영역 S -->';
str+='              <div class="allmenu-wrapper">';
str+='                  <div class="ios"><!-- [개발자 전달] 스크롤 버그 수정용 -->';       
str+='                      <div class="allmenu-top"><!-- [개발자 전달] 디자인 변경되었습니다 S -->';
str+='                          <div class="menu_area">';
str+='                              <div class="user_info">';    
str+='                                  <p><span class="user_nm">김농협</span>님</p>';
str+='                              </div>';                    
str+='                              <ul class="top_menu">';
str+='                                  <li class="prof">';
str+='                                      <a href="javascript:void(0);" role="button"><span class="text_over">김농협 프로필</span></a>';
str+='                                  </li>';
str+='                                  <li class="alram">';
str+='                                      <a href="javascript:void(0);" class="active" title="새알림" role="button"><span class="text_over">알림</span></a><!-- [개발자 전달] 알림 있으면 class active 추가하세요 -->';
str+='                                  </li>';
str+='                              </ul>';
str+='                          </div>';
str+='                          <div>';
str+='                              <ul class="section_list">';                  
str+='                                  <li class="wPc100">';
str+='                                      <a href="javascript:void(0);" class="bg_white" role="button">';
str+='                                          <span class="list_box all">';
str+='                                              <span class="list_tit">자산기관관리</span>';
str+='                                          </span>';
str+='                                      </a>';
str+='                                  </li>';                 
str+='                              </ul>';
str+='                          </div>';
str+='                          <div>';
str+='                              <ul class="section_list">';                  
str+='                                  <li class="wPc100">';
str+='                                      <a href="javascript:void(0);" class="bg_white" role="button">';
str+='                                          <span class="list_box all credit">';
str+='                                              <span class="list_tit">나의신용점수</span>';
str+='                                              <span class="list_num">940<em>점</em></span>';
str+='                                          </span>';
str+='                                      </a>';
str+='                                  </li>';                 
str+='                              </ul>';
str+='                          </div>';
str+='                      </div><!-- // [개발자 전달] 디자인 변경되었습니다 E -->';
str+='                      <div class="com_inner credit_list_box all_Menu">';
str+='                          <div class="com_box_nobox">';
str+='                              <div class="list_type_box">';
str+='                                  <div class="new_tit_area">';
str+='                                      <div class="tit"><span>나의자산</span></div>';
str+='                                  </div>';
str+='                                  <ul class="list_type_02">';
str+='                                      <li><a href="javascript:void(0);">전체</a></li>';
str+='                                      <li><a href="javascript:void(0);">자산</a></li>';
str+='                                      <li><a href="javascript:void(0);">부채</a></li>';
str+='                                      <li><a href="javascript:void(0);">진단</a></li>';
str+='                                  </ul>';
str+='                              </div>';
str+='                          </div>';
str+='                          <div class="com_box_nobox">';
str+='                              <div class="list_type_box">';
str+='                                  <div class="new_tit_area">';
str+='                                      <div class="tit"><span>가계부</span></div>';
str+='                                  </div>';
str+='                                  <ul class="list_type_02">';
str+='                                      <li><a href="javascript:void(0);">달력</a></li>';
str+='                                      <li><a href="javascript:void(0);">지출</a></li>';
str+='                                      <li><a href="javascript:void(0);">분석</a></li>';
str+='                                  </ul>';
str+='                              </div>';
str+='                          </div>';
str+='                          <div class="com_box_nobox">';
str+='                              <div class="list_type_box">';
str+='                                  <div class="new_tit_area">';
str+='                                      <div class="tit"><span>금융생활</span></div>';
str+='                                  </div>';
str+='                                  <ul class="list_type_02">';
str+='                                      <li><a href="javascript:void(0);">나의목표</a></li>';
str+='                                      <li><a href="javascript:void(0);">상품추천</a></li>';
str+='                                      <li><a href="javascript:void(0);">자동차</a></li>';
str+='                                  </ul>';
str+='                              </div>';
str+='                          </div>';
str+='                          <div class="com_box_nobox">';
str+='                              <div class="list_type_box">';
str+='                                  <div class="new_tit_area">';
str+='                                      <div class="tit"><span>마이농가</span></div>';
str+='                                  </div>';
str+='                                  <ul class="list_type_02">';
str+='                                      <li><a href="javascript:void(0);">영농달력</a></li>';
str+='                                      <li><a href="javascript:void(0);">영농일지</a></li>';
str+='                                      <li><a href="javascript:void(0);">농기계임대</a></li>';
str+='                                      <li><a href="javascript:void(0);">정책자금</a></li>';
str+='                                      <li><a href="javascript:void(0);">조합원</a></li><!-- [개발자 전달] 조합원이 있을 때 노출하세요. -->';
str+='                                      <li><a href="javascript:void(0);">설정</a></li>';
str+='                                  </ul>';
str+='                              </div>';
str+='                          </div>';
str+='                      </div>';
str+='                      <div class="com_inner credit_list_box all_Menu com_bg_type02">';
str+='                          <div class="com_btn_area">';
str+='                              <a href="javascript:void(0);" class="com_btn_round"><span class="ico type03">자산관리 서비스 안내</span></a>';
str+='                          </div>';
str+='                          <div class="com_btn_area">';
str+='                              <a href="javascript:void(0);" class="com_btn_round"><span class="ico type04">마이농가 이용안내</span></a>';
str+='                          </div>';
str+='                      </div>';
str+='                      <div class="closed-wrap all_Menu">';
str+='                          <ul>';
str+='                              <li><a href="javascript:void(0);">새소식</a></li>';
str+='                              <li><a href="javascript:void(0);">자주하는질문</a></li>';
str+='                              <li><a href="javascript:void(0);">숨김보관함</a></li>';
str+='                              <li><a href="javascript:void(0);">이용약관</a></li>';
str+='                          </ul>';
str+='                          <ul class="mt15">';
str+='                              <li><a href="javascript:void(0);">제3자정보제공동의</a></li>';
str+='                              <li><a href="javascript:void(0);"><strong class="txt_black">개인정보처리방침</strong></a></li>';
str+='                              <li><a href="javascript:void(0);">서비스해지</a></li>';
str+='                          </ul>';            
str+='                      </div>';            
str+='                  </div>';
str+='                  <!-- 닫기 S -->';
str+='                  <div class="com_btn_area all_Menu">';
str+='                      <a href="javascript:void(0);" class="all_close"><span class="blind">전체메뉴닫기</span></a>';
str+='                  </div>';   
str+='                  <!--// 닫기 E -->';
str+='              </div>';
str+='              <!-- //전체메뉴 영역 E -->';

document.write(str);


})();